### ISSUE TITLE
RPC error when deleting node

### ISSUE THREAD

**Issue by EtiennePhillipsBeckhoff** [Mobject-Dev-Team/mobject-graph#11]
As a node is deleted, mobject-graph-webserver reports the following RPC error:

```
Error calling RPC method GetStatus: Error: Call 185: Unknown UUID : c0874bcf-4a4d-4e5d-b260-d0a8ff09e243
    at #handleFailure (C:\Temp\repos\mobject\mobject-graph-webserver\node_modules\mobject-client\src\core\AsyncClient.js:298:29)
    at #handleResponseBasedOnStatus (C:\Temp\repos\mobject\mobject-graph-webserver\node_modules\mobject-client\src\core\AsyncClient.js:166:28)
    at #enqueueRequest (C:\Temp\repos\mobject\mobject-graph-webserver\node_modules\mobject-client\src\core\AsyncClient.js:118:68)
```

Node is still deleted successfully though, and no side-effects have been noticed.

**Comment by benhar-dev** [comment]
Fixed in previous version
